[versions]
agp = "9.1.1"
kotlin = "2.3.21"
rhino = "1.9.1"
shizuku = "13.1.5"

[libraries]
rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }
shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "shizuku" }
shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "shizuku" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }